### ISSUE TITLE
000 - The app doesn't display any source data

### ISSUE THREAD

**Issue by ilyapavlovdx** [doichenzeldaten/DataGrid#1]
Hi,
On my PC, the app displays just empty space in the console, and the caret is displayed below the space.
![image](https://user-images.githubusercontent.com/26572971/60394961-ce1b2180-9b34-11e9-9374-40f77e66aac7.png)

While debugging, I noticed that _ParsResults contains objects with empty fields. However, the source file is loaded successfully.
![image](https://user-images.githubusercontent.com/26572971/60395023-cdcf5600-9b35-11e9-8561-f8216f52bf0f.png)

Please fix the shit.

**Comment by AlexanderSharygin** [comment]
The shit is fixed.
Shit had been stinks because I factored in as newline only characters "\n\r". I forgout what thats characters also can be: '\r', '\n' and '\n\r'. Now i fixed this issue. 
![joxi_screenshot_1561902588500](https://user-images.githubusercontent.com/52005798/60397581-26631b00-9b57-11e9-8c21-613f2aed2289.png)

**Comment by ilyapavlovdx** [comment]
ok
